spring.application.name=java-agent-learning
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.init.pull-model-strategy=always
spring.ai.ollama.init.timeout=60s
spring.ai.ollama.init.max-retries=1
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL:qwen2.5:7b}
spring.ai.ollama.chat.options.temperature=${OLLAMA_TEMPERATURE:0.7}

spring.output.ansi.enabled=always

server.tomcat.uri-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true

spring.main.allow-bean-definition-overriding=true

spring.autoconfigure.exclude[0]=dev.langchain4j.ollama.spring.AutoConfig

# Ollama
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen2.5:7b

# apiKey
spring.ai.dashscope.api-key=sk-f8d147e3b7b04bee8a952097ab3ad4dc

# deepseek
deepseek.api-key=sk-xxxxxxxxxxxxxxxx
deepseek.base-url=https://api.deepseek.com
deepseek.model=deepseek-chat
deepseek.max-tokens=2048